title: ChaoliangTang
logo: /assets/img/logo.jpg
description: I am a PhD student in Fudan University, supervised by Professor Hehui Wu.
favicon: true
color-scheme: auto

# 邮箱配置（关键修改）
contact:
  emails:
    - address: chaoliang.tang@ens-lyon.fr
      icon: /assets/img/logo.jpg
    - address: cltang22@m.fudan.edu.cn
      icon: /assets/img/logo.jpg
      

# plugins:
#   - jekyll-sitemap
#   - jekyll-seo-tag
#   - jemoji

# platforms:
#   - name: GitHub
#     icon: <i class="fa-brands fa-github"></i>
#     link: https://github.com/vaibhavvikas
#   - name: LinkedIn
#     icon: <i class="fa-brands fa-linkedin"></i>
#     link: https://www.linkedin.com/in/vaibhavvikas

# navigation:
#   - name: Readme
#     link: ./index.html
#     sublist:
#       - name: Image
#         link: ./index.html#small-image
#   - name: Another Page
#     link: ./another-page.html
